# Generated by Django 5.0.4 on 2024-04-19 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_alter_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
