# Generated by Django 5.0.4 on 2024-04-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staff_address_staff_email_alter_staff_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='address',
            new_name='adress',
        ),
    ]
